version: '3.8'

services:
  app:
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://os_ia:${DB_PASSWORD}@db:5432/os_ia_prod
    depends_on:
      - db
    networks:
      - os_ia_network

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=os_ia
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=os_ia_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - os_ia_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - app
    networks:
      - os_ia_network

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - os_ia_network

  grafana:
    image: grafana/grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - os_ia_network

networks:
  os_ia_network:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:
  grafana_data: